# -- WebGoat.NET Vulnerable .net application --
#
# Example Veracode Scan in Azure Pipelines
# The pipeline will perform SCA + SAST Policy Scan on the Main branch
# Scan Results and Findings are imported into Azure DevOps Boards

trigger:
  branches:
    include: [azure-integration]

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  group: VeracodeScanning

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/WebGoat/bin'
    IncludeRootFolder: true
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/bin.zip'
    replaceExistingArchive: true
    verbose: true
